services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: g-settings-frontend
    hostname: g-settings-frontend
    image: g-settings-frontend:0.0.1
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      galaxy:
        ipv4_address: 192.168.200.170
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  galaxy:
    external: true
