# .pre-commit-config.yaml
exclude: >
  (?x)^(
    .*__init__\.py|
    .*settings\.py|
    .*wsgi\.py|
    .*asgi\.py
  )$

repos:
  # Format Python code
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.10

  # Sort Python imports
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python import sorter)

  # Lint Python code
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        args: ["--max-line-length=120"]

  # Python security scanner
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-r", "backend/src/"]

  # Frontend: ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.27.0
    hooks:
      - id: eslint
        types: [javascript, jsx]
        additional_dependencies: [eslint, eslint-config-prettier]
        args: ["--fix"]


  # Frontend: Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [javascript, jsx, css, html, json]
        args: ["--write"]

  # General cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
