# .pre-commit-config.yaml
exclude: >
  (?x)^(
    .*__init__\.py|
    .*settings\.py|
    .*wsgi\.py|
    .*asgi\.py
  )$

repos:
  # Sort Python imports (run isort before black)
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python import sorter)
        args: [--profile=black, --line-length=88]

  # Format Python code
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.10

  # Lint Python code
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        args: ["--max-line-length=88"]

  # Python security scanner
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-r", "backend/src/"]

  # Frontend: ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.13.0
    hooks:
      - id: eslint
        types: [javascript, jsx]
        additional_dependencies: [eslint, eslint-config-prettier]
        args: ["--fix"]

  # Frontend: Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [javascript, jsx, css, html, json]
        args: ["--write"]

  # General cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
