services:
  core:
    build:
      context: .
      dockerfile: dockerfile
    container_name: core
    hostname: core
    image: core:0.0.1
    volumes:
      - media_volume:/app/src/media_volume
      - static_volume:/app/src/media_volume
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "8004:8000"
    networks:
      galaxy:
        ipv4_address: 192.168.200.43
    restart: unless-stopped
    env_file:
      - ./.env
    command: bash initialize/settings_initialize.sh
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/settings/api/schema/swagger-ui/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

networks:
  galaxy:
    external: true

volumes:
  media_volume:
    name: settings-media-volume
  static_volume:
    name: settings-static-volume
