services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core
    hostname: core
    image: core:0.0.1
    volumes:
      - media_volume:/app/src/media_volume
      - static_volume:/app/src/media_volume
      - ./src/apps/todo/migrations:/app/src/apps/todo/migrations
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./.env
    command: bash initialize/core_initialize.sh


networks:
  core:
    external: true

volumes:
  media_volume:
    name: core-media-volume
  static_volume:
    name: core-static-volume
