services:
  core-data:
    image: postgres:16.3-alpine3.18
    container_name: core-cdb
    hostname: core-data
    env_file:
      - ./secrets/.env
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - core_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "5432:5432"
    networks:
      - core
    restart: unless-stopped

networks:
  core:
    external: true

volumes:
  core_data:
    name: core_data
